keys:
  - &heavy_user age178f7dvqqr4r2k06fj3u5lrmg4n4qzu5u2q03vwjes42n5dajnaeshxnn69
  - &heavy_host age1lakwj5gtc8sjksshhy850eqeh4ac7gkp39xecqhngaldr5xj7ayqvz6yj3
  - &beast_user age1df073aud9a2y8rukr553cln9a75cfw30nh4czytaemjgsmnuh3sszktve0
  - &beast_host age14002ye36h029nh99wqwv8j7kacydsscplf6mkl6mmfgm6lyxlsys88jhvt
  - &vm_host age10qy3hjv9lh8r3eyqgkplsd2mg583tj93vyxn00jn3ly9fv64l9ss627gu8

creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
        - age:
            - *heavy_user
            - *heavy_host
            - *beast_user
            - *beast_host
            - *vm_host
