keys:
  - &heavy_user age178f7dvqqr4r2k06fj3u5lrmg4n4qzu5u2q03vwjes42n5dajnaeshxnn69
  - &heavy_host age1lakwj5gtc8sjksshhy850eqeh4ac7gkp39xecqhngaldr5xj7ayqvz6yj3

creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
        - age:
            - *heavy_user
            - *heavy_host
