# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ "ntsync" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/5ce1c681-67e8-43c8-885b-7586d97419f1";
      fsType = "btrfs";
      options = [ "rw" "subvol=@" "noatime" "compress-force=zstd:2" "space_cache=v2" ];
    };

  boot.initrd.luks.devices."root".device = "/dev/disk/by-uuid/cc4f3a69-462c-4849-9d1e-9368191f3810";

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/5ce1c681-67e8-43c8-885b-7586d97419f1";
      fsType = "btrfs";
      options = [ "rw" "subvol=@home" "noatime" "compress-force=zstd:2" "space_cache=v2" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/5ce1c681-67e8-43c8-885b-7586d97419f1";
      fsType = "btrfs";
      options = [ "rw" "subvol=@log" "noatime" "compress-force=zstd:2" "space_cache=v2" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/65C7-D9AD";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
